apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata: {name: github-push-binding, namespace: demo}
spec:
  params:
    - name: repo-url
      value: $(body.repository.clone_url)
    - name: revision
      value: $(body.after)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata: {name: github-push-template, namespace: demo}
spec:
  params:
    - name: repo-url
    - name: revision
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata: {generateName: jx-demo-run-}
      spec:
        pipelineRef: {name: jx-demo-pipeline}
        params:
          - {name: repo-url, value: $(tt.params.repo-url)}
          - {name: revision, value: $(tt.params.revision)}
          - {name: image, value: "ghcr.io/malbaqari/jx-demo-app:$(tt.params.revision)"}
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes: [ReadWriteOnce]
                resources: {requests: {storage: 1Gi}}
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata: {name: github-listener, namespace: demo}
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: github-push
      bindings:
        - {ref: github-push-binding}
      template: {ref: github-push-template}
